name: kuwa
services:
  web:
    image: kuwaai/multi-chat-web
    build:
      context: ../../
      dockerfile: docker/web/Dockerfile
    restart: unless-stopped
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
    volumes: ["multi-chat-storage:/app/storage:ro"]
    ports: ["80:80", "443:443"]
    depends_on: ["multi-chat"]
    networks: ["frontend"]
    healthcheck:
      test: ["CMD-SHELL", "curl", "-f", "http://localhost/"]
      timeout: 10s
  
  multi-chat:
    image: kuwaai/multi-chat
    build:
      context: ../../
      dockerfile: docker/multi-chat/Dockerfile
    restart: unless-stopped
    init: true
    depends_on:
      - redis
    environment:
      APP_ENV: production
      APP_DEBUG: false
      APP_URL: ${PUBLIC_BASE_URL}

      # Use sqlite as the default database
      DB_CONNECTION: sqlite
      DB_DATABASE: /app/storage/database.sqlite

      ADMIN_NAME: ${ADMIN_NAME}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD_FILE: /run/secrets/admin-password
    secrets:
      - admin-password
    volumes: [
      "multi-chat-storage:/app/storage:rw",
      "../root/custom:/app/resources/views/components/custom:ro",
      "../root/bootstrap/bot:/var/kuwa/docker/root/bootstrap/bot:ro",
    ]
    healthcheck:
      test: ["CMD-SHELL", "php-fpm-healthcheck"]
      timeout: 10s
    networks: ["frontend", "backend"]

  kernel:
    image: kuwaai/kernel
    build:
      context: ../../
      dockerfile: docker/kernel/Dockerfile
    restart: unless-stopped
    networks: ["backend"]

  redis:
    image: redis:6.0.20
    restart: always
    networks:
      - backend

  executor-builder:
    image: kuwaai/model-executor
    build:
      context: ../../
      dockerfile: docker/executor/Dockerfile
    entrypoint: /bin/bash -c
    command: ["echo Image builds completed."]

volumes:
  multi-chat-storage: {}
  kuwa-root: # The root of Kuwa filesystem hierarchy to store user-uploaded data during runtime.
    driver: local
    driver_opts:
      type: none
      device: "../root"
      o: bind

secrets:
  admin-password:
    file: ../.admin-password

networks:
  frontend: {}
  backend: {}