services:
  multi-chat:
    environment:
      APP_ENV: development
      APP_DEBUG: true
  # db-ui:
  #   image: adminer
  #   restart: always
  #   depends_on:
  #     - db
  #   ports:
  #     - 8081:8080
  #   environment:
  #     ADMINER_DEFAULT_SERVER: db
  #   networks:
  #     - backend