services:
  multi-chat:
    depends_on:
      - db
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD_FILE: /run/secrets/db-password
      DB_DATABASE: ${DB_DATABASE}
    secrets:
      - db-password

  db:
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD_FILE: /run/secrets/db-password
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - mysql-data:/var/lib/mysql
    secrets:
      - db-password
    networks:
      - backend

  # db-ui:
  #   image: adminer
  #   restart: unless-stopped
  #   depends_on:
  #     - db
  #   ports:
  #     - 8080:8080
  #   networks:
  #     - backend

volumes:
  mysql-data: {}

secrets:
  db-password:
    file: .db-password